Determining if the function pow exists failed with the following output:
Change Dir: /home/zhangbinggang/workspace/personal_github/HappyLearningML/LearningCMake/tutorial_six/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_bfe67/fast && /usr/bin/make -f CMakeFiles/cmTC_bfe67.dir/build.make CMakeFiles/cmTC_bfe67.dir/build
make[1]: Entering directory '/home/zhangbinggang/workspace/personal_github/HappyLearningML/LearningCMake/tutorial_six/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_bfe67.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pow   -o CMakeFiles/cmTC_bfe67.dir/CheckFunctionExists.c.o   -c /home/zhangbinggang/anaconda3/lib/python3.7/site-packages/cmake/data/share/cmake-3.15/Modules/CheckFunctionExists.c
<command-line>:0:23: warning: conflicting types for built-in function ‘pow’
/home/zhangbinggang/anaconda3/lib/python3.7/site-packages/cmake/data/share/cmake-3.15/Modules/CheckFunctionExists.c:7:3: note: in expansion of macro ‘CHECK_FUNCTION_EXISTS’
   CHECK_FUNCTION_EXISTS(void);
   ^
Linking C executable cmTC_bfe67
/home/zhangbinggang/anaconda3/lib/python3.7/site-packages/cmake/data/bin/cmake -E cmake_link_script CMakeFiles/cmTC_bfe67.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pow    CMakeFiles/cmTC_bfe67.dir/CheckFunctionExists.c.o  -o cmTC_bfe67 
CMakeFiles/cmTC_bfe67.dir/CheckFunctionExists.c.o: In function `main':
CheckFunctionExists.c:(.text+0x10): undefined reference to `pow'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_bfe67.dir/build.make:86: recipe for target 'cmTC_bfe67' failed
make[1]: *** [cmTC_bfe67] Error 1
make[1]: Leaving directory '/home/zhangbinggang/workspace/personal_github/HappyLearningML/LearningCMake/tutorial_six/CMakeFiles/CMakeTmp'
Makefile:121: recipe for target 'cmTC_bfe67/fast' failed
make: *** [cmTC_bfe67/fast] Error 2



